# Generated by Django 3.2.3 on 2023-06-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230624_1805'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='favorite_unique',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='shoppingcart_unique',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='uniq_favorite'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='uniq_shoppingcart'),
        ),
    ]
